// Generated by CoffeeScript 1.7.1
(function() {
  var FileSystem, Liquid, Promise, fs, path;

  Liquid = require("../liquid");

  Promise = require("bluebird");

  fs = require("fs");

  path = require("path");

  module.exports = FileSystem = (function() {
    function FileSystem(root) {
      this.root = root;
    }

    FileSystem.prototype.readTemplateFile = function(template_path, context) {
      var fullPath;
      fullPath = this.lookupFullPath(template_path);
      return Promise.promisify(fs.readFile)(fullPath);
    };

    FileSystem.prototype.lookupFullPath = function(lookupPath) {
      return path.join(this.root, lookupPath);
    };

    return FileSystem;

  })();

}).call(this);

//# sourceMappingURL=file_system.map
